### ISSUE TITLE
Info about upcoming removal of packages in the General registry

### ISSUE THREAD

**Issue by KristofferC** [MikeInnes/TakingBroadcastSeriously.jl#10] opened 2019-09-04 19:18 UTC
As described in https://discourse.julialang.org/t/ann-plans-for-removing-packages-that-do-not-yet-support-1-0-from-the-general-registry/ we are planning on removing packages that do not support 1.0 from the General registry. This package has been detected to not support 1.0 and is thus slated to be removed. The removal of packages from the registry will happen approximately a month after this issue is open.

To transition to the new Pkg system using `Project.toml`, see https://github.com/JuliaRegistries/Registrator.jl#transitioning-from-require-to-projecttoml.
To then tag a new version of the package, see https://github.com/JuliaRegistries/Registrator.jl#via-the-github-app.

If you believe this package has erroneously been detected as not supporting 1.0 or have any other questions, don't hesitate to discuss it here or in the thread linked at the top of this post.

**Comment by oxinabox** [comment] 2019-09-04 20:15
Broadcasting has successfully been taken seriously now, so good?

**Comment by MikeInnes** [comment] 2019-09-05 11:51
Yup, I think we're pretty serious now.

Is it safe to delete this repo, either before removal or after? Or should we move it to JuliaAttic?

**Comment by oxinabox** [comment] 2019-09-05 12:48
Just archive it, and leave it in your account
that way you don't break reproducability of my papers using TensorFlow.jl in julia 0.6 that still use Metadata.
https://help.github.com/en/articles/archiving-repositories

**Comment by MikeInnes** [comment] 2019-09-05 12:51
I think moving it to JuliaAttic and changing the URL in METADATA would be OK for that, right?

**Comment by oxinabox** [comment] 2019-09-05 12:54
seems like way more work than just clicking the archive button in settings though?

**Comment by MikeInnes** [comment] 2019-09-05 12:57
It'll be safer. If it's not properly archived I'll forget about this conversation and end up deleting it at some point.

**Comment by oxinabox** [comment] 2019-09-05 12:59
why would anyone ever delete anything ever?
Weird.
But fair enough

**Comment by oxinabox** [comment] 2019-09-05 13:00
Probably don't actually need to change Metadata since Github will make redirects anyway

**Closed as completed** 2019-10-09 08:28 UTC
